### PR TITLE
Remove extra asterisks from PURPOSE.md?

### PR DESCRIPTION
**Pull request by zgoethel**
I noticed that you had the following header:
### Sample*\* **setup

and it bothered me, so I offer my services.  Perhaps it was on purpose.

### CODE REVIEW

**Comment by bruienne** [comment]
Looks like a leftover from converting it with another MD tool, that doesn't belong there, you're right.

**Comment by zgoethel** [comment]
Will you merge?

**Comment by bruienne** [comment]
I can, but you closed to PR before I had a chance...

**Comment by bruienne** [comment]
s/to/the

**Comment by zgoethel** [comment]
Yeah, thought it was too small to warrant a pull request and I was in the middle of cleaning up my account.

**Pull request closed without merging**
